# Using 1a9 as postfix to avoid conflicts with containers and images that already exist in Docker
version: '1'
services:
  client-backend:
    depends_on:
      - client-db
    container_name: client-backend-1a9
    build:
      context: ./client-backend/.
    ports:
      - 8080:8080

  client-db:
    container_name: client-db-1a9
    build:
      context: ./client-db/.
    ports:
      - 3306:3306

